backend:
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "about"
        label: "Waldsee Camping Bettmar"
        file: "src/data/about.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Beschreibung, name: description, widget: string }
      - name: "services"
        label: "Unsere Leistungen"
        file: "src/data/services.yml"
        fields:
          [
            {
              label: Stellplätze,
              name: stellplaetze,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Zeltplätze,
              name: zeltplaetze,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Ferienhäuser,
              name: ferienhaeuser,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Jahresplätze,
              name: jahresplaetze,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Spielplatz,
              name: spielplatz,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Sanitäranlagen,
              name: sanitaeranlagen,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: file },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: See,
              name: see,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Grillen,
              name: grillen,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Hunde,
              name: hunde,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Nahrverkehr,
              name: nahrverkehr,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
            {
              label: Service,
              name: service,
              widget: object,
              fields:
                [
                  { label: Titel, name: title, widget: string },
                  { label: Images, name: images, widget: image },
                  { label: Beschreibung, name: description, widget: text },
                ],
            },
          ]
      - name: "gallery"
        label: "Galerie"
        file: "src/data/gallery.yml"
        fields:
          - {
              label: Galerie,
              name: data,
              widget: list,
              fields:
                [
                  { label: Bilder, name: file, widget: image },
                  {
                    label: Beschreibung,
                    name: description,
                    widget: string,
                    required: false,
                  },
                ],
            }
      - name: "site_infos"
        label: "Seiten Infos"
        file: "src/data/site-infos.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Besitzer, name: owner, widget: string }
          - { label: Adresse, name: adress, widget: string }
