backend:
  name: git-gateway
  branch: master

media_folder: "/src/assets/uploads"
public_folder: "/src/assets/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "about"
        label: "Waldsee Camping Bettmar"
        file: "src/data/about.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Beschreibung, name: description, widget: string }
      - name: "services"
        label: "Unsere Leistungen"
        file: "src/data/services.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Bilder, name: images, widget: image }
          - { label: Beschreibung, name: description, widget: string }
      - name: "gallery"
        label: "Galerie"
        file: "src/data/gallery.yml"
        fields:
          - { label: Bild, name: file, widget: image }
          - { label: Beschreibung, name: description, widget: string }
